Create CODE_OF_CONDUCT.md
takanome-dev/blog-with-astro-golang pull request #45
Opened 2023-10-02 18:19 UTC by Madhvik007

- [✔ ] 📝 Documentation Update

This PR adds CODE_OF_CONDUCT.md

This PR Fixes issue number #44

2023-10-02 19:48 UTC, takanome-dev requested changes
Thanks for opening this pr, @Madhvik007. I updated the pr template 👌
Just a couple of changes and this should be good to go :rocket: 

Please add the attribution section at the end of the file

![2023-10-02_19-41](https://github.com/takanome-dev/blog-with-astro-golang/assets/79809121/2e99d19a-338e-4e34-89d6-f1c85f2271d9)

2023-10-02 19:48 UTC, takanome-dev commented on CODE_OF_CONDUCT.md
> +[INSERT CONTACT METHOD].
```suggestion
reported by contacting the project owner at [takanomedev@duck.com](mailto:takanomedev@duck.com)
```

2023-10-03 10:18 UTC, Madhvik007 commented
I've made the changes. Is there anything else you'd like me to do?

2023-10-03 11:00 UTC, takanome-dev approved these changes
LGTM

2023-10-03 11:01 UTC, takanome-dev commented
> I've made the changes. Is there anything else you'd like me to do?

No, everything looks good. Thanks again :+1:

2023-10-03 11:05 UTC, merged